# Generated by Django 5.0.4 on 2024-09-17 14:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Photoshoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('shooting_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата Съемки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallerys.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фотосъемку',
                'verbose_name_plural': 'Фотосъемки',
                'db_table': 'photoshoot',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallerys_images/', verbose_name='Фотография')),
                ('photoshoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallerys.photoshoot', verbose_name='Фотосъемка')),
            ],
            options={
                'verbose_name': 'Фотографию',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photo',
                'ordering': ('id',),
            },
        ),
    ]
