# Generated by Django 5.0.4 on 2024-09-18 23:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoshoot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallerys.photoshoot', verbose_name='Фотосъемка'),
        ),
        migrations.AlterField(
            model_name='photoshoot',
            name='shooting_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата Съемки'),
        ),
    ]
